import { createBrowserRouter, RouterProvider } from 'react-router-dom'
import Home from './routes/Home/index.jsx'
import Produtos from './routes/Produtos/Index.jsx'
import EditarProdutos from './routes/EditarProdutos/Index.jsx'
import Error from './routes/Error/Index.jsx'
